### ISSUE TITLE
Minimize/don't load review history & map on profile page until called upon

### ISSUE THREAD

**Issue by mdooley98** [MrJPGames/WayFarerPlus#151]
**Describe the feature you'd like**
Have the review history & map not loaded by default, only load when asked to

**Describe reasons NOT to add this feature**
I'm not entirely certain it's possible or if it'd solve the loading speed issue.

**Describe reasons to add this feature**
I have 1500 reviews in my history now and it stalls out for 3-4 seconds each time I open my /profile page as it loads in all the history.

**Additional context**
I can send my review history json/csv over discord if it helps for replicating the issue

**Comment by MrJPGames** [comment]
I never saw the slow loading as much of an issue. But you are right. This will be looked into!

It seems likely the new default will become that it's not loaded until a button is hit or something. This is because due to the storage solution used the page has to wait for all the data to load before it can continue. Though maybe the slowness comes from the processing in which case it might be possible to optimise the loading and leave the map on by default. 

I'm currently busy so I can't give any ETA on when this will be done sadly.

**Comment by MrJPGames** [comment]
From 1c41ec7451fd9dd30e22861e6d97d178ce95843e onward the user needs to choose a UID. As such there won't be a load on page load (if I'm not forgetting something). As such this issue will be closed as it should be fixed in the next update. Feel free to request reopening or open a new issue if there are still problems with this solution!
