### ISSUE TITLE
Browser notification for submit button lock timer

### ISSUE THREAD

**Issue by Roli0109** [MrJPGames/WayFarerPlus#172]
**Describe the feature you'd like**
Display a notification when the lock timer has finished. (Probably best to only do it when tab is not currently viewed)

**Describe reasons NOT to add this feature**
Most users don't use a timer so long this feature would add much utility

**Describe reasons to add this feature**
For those running longer timers this can allow them to do other tasks while waiting for the timer to finish. It should probably be disabled by default however.

**Additional context**
Original text:
If the Lock submit button expires, **I will receive a browser notification.**

If you have a good idea then please let me know

**Comment by MrJPGames** [comment]
A different feature with the same purpose has been created. It plays a sound when the lock timer expires. In the next update this can be enabled from settings (the update is not finished/released as of writing this comment).

If you really want a notification, rather than notification sound feel free to reopen this issue, or open a new issue.
