### ISSUE TITLE
Add Apple Maps via DuckDuckGo

### ISSUE THREAD

**Issue by hdort** [MrJPGames/WayFarerPlus#178]
I'd like to suggest to add Apple Maps via DuckDuckGo to the maps drop down. I find it really helpful to check a location on different maps, especially when no StreetView is available.

Thanks for a nice extension, keep up the great work! :)

**Comment by MrJPGames** [comment]
Hi, you can already add your own custom maps. In WF+ settings (accessed through the toolbar icon) under "Open in configuration" you can add, remove and import custom maps. I have created the Apple Maps via DuckDuckGo config here. Due to GitHubs limits on what file extensions are allowed here you will need to change the file extension from .txt to .wfpm for WF+ to be able to open the file.

[Apple maps.txt](https://github.com/MrJPGames/WayFarerPlus/files/4797591/Apple.maps.txt)

If you have good arguments as to why the use of Apple maps should be included in WF+ by default please let me know and I will consider it. But for now I'll consider this issue closed.
