### ISSUE TITLE
[BUG] Adding Presets doesn't work

### ISSUE THREAD

**Issue by SfSuicune** [MrJPGames/WayFarerPlus#98]
Hi

**Describe the bug**
When I try to add a preset, nothing happens after pressing "OK". My preset bar has 2 settings right now. I didn't try an empty one.
Removing a preset works though.

Reinstalling the addon doesn't help fixing the issues.

**Expected behavior**
Presets to be set as described in the Wiki.

**Browser**
Latest Chrome x64 Version on Win7

**Comment by MrJPGames** [comment]
I'll investigate this issue soon. In the mean time you could help me by providing some steps to reproduce this issue. Did you set the WhatIsIt box, yes or no? What star ratings did you give and which ones did you not. Is there a incorrect limit at 2, not allowing you to add any more than that number?

Also as you can see I've removed a separate issue you added onto this bug report and migrated it for you to #99

**Comment by SfSuicune** [comment]
I set nothing in that "What is it" box. Also added no additional comment.
No matter what rating I set anywhere and what not, the preset doesn't get added. Whether I rate everything or just the photo.
I removed my presets to 0, so don't have any right now. It doesn't change anything about the issue.

**Comment by MrJPGames** [comment]
Thanks! Not setting the WhatIsIt box was indeed the issue.
As you can see I was actually already able to resolve the issue. There was a bug that made it so a what is it box setting was required. Later today I will push this fix, it will be available for Firefox later today as a result Chrome usually takes 0-4 days to review, so that will likely take a little longer.

**Comment by SfSuicune** [comment]
Great that it has been solved fast! :D
